- name: run shell script
  shell: |
         #!/bin/bash
         cd /home/drai96005/ansizal
         #sudo docker rm $(sudo docker ps -a -q)
         #sudo docker rmi $(sudo docker images -q)
         sudo docker container prune -f
         sudo docker image prune -f
         sudo docker build --build-arg url=https://github.com/deepshikharai/PHP-trav-simple.git --build-arg path=PHP-trav-simple/PHP_traveller/ --build-arg artifactid=PHP_traveller --build-arg version=0.0.1 -t zalphp .
         sleep 2m

- name: run docker images
  shell: |
         #!/bin/bash
         sudo docker run zalphp>>~/reports/selenium.log
  
        
